GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2NjIxMzRhM2Q2MThhOWEzMTYwN2Q0MzUiLCJpYXQiOjE3MTM0NTM4MzR9.Cj84YljkGOUaf4nyN0uGsgnB4TfAcGSXiGeBXMW2T28

###

DELETE http://localhost:3001/api/blogs/6621362cc776ca2ae324632f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2NjIxMzRhM2Q2MThhOWEzMTYwN2Q0MzUiLCJpYXQiOjE3MTM0NTM4MzR9.Cj84YljkGOUaf4nyN0uGsgnB4TfAcGSXiGeBXMW2T28


###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Sora",
    "author": "methane",
    "url": "wwww.youtube.com",
    "likes": 5
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxvIiwiaWQiOiI2NjIxMzRhM2Q2MThhOWEzMTYwN2Q0MzUiLCJpYXQiOjE3MTM0NTM4MzR9.Cj84YljkGOUaf4nyN0uGsgnB4TfAcGSXiGeBXMW2T28

{
    "title": "ano hi",
    "author": "meth",
    "url": "wwww.youtube.com",
    "likes": 3
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Sora",
    "author": "keta",
    "url": "wwww.youtube.com",
    "userId": "661fd5da7443f76a562704e9"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "hello",
    "name": "kenobi",
    "password": "there"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": ""
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "ha",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "pa"
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "hello",
    "password": "there"
}

###
GET http://localhost:3001/api/persons/660904a76346a9ae100f7458

###
PUT http://localhost:3001/api/blogs/661b809c547cc7885529d53c HTTP/1.1
Content-Type: application/json

{
 "likes": 10
}