GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/blogs/661b80f918952f3699cbe635


###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Sora",
    "author": "methane",
    "url": "wwww.youtube.com",
    "likes": 5
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciiiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2MWZkNWRhNzQ0M2Y3NmE1NjI3MDRlOSIsImlhdCI6MTcxMzM2NjgxNn0.Wy0m1KVhRH-L9DBSBSuDXoC8KrTALBjYracLUCxw4M8

{
    "title": "Sora",
    "author": "keta",
    "url": "wwww.youtube.com",
    "likes": 5
}

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "Sora",
    "author": "keta",
    "url": "wwww.youtube.com",
    "userId": "661fd5da7443f76a562704e9"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": ""
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "ha",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "Superuser",
    "password": "pa"
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}

###
POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "groot",
    "password": "salainen"
}

###
GET http://localhost:3001/api/persons/660904a76346a9ae100f7458

###
PUT http://localhost:3001/api/blogs/661b809c547cc7885529d53c HTTP/1.1
Content-Type: application/json

{
 "likes": 10
}