GET http://localhost:3001/api/persons

###

DELETE http://localhost:3001/api/persons/6606beda49c76a1dd8ca1301


###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "methane",
    "number": "999"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "methane",
    "number": "111"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "methane"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "number": "999"
}

###
GET http://localhost:3001/api/persons/660904a76346a9ae100f7458